### ISSUE TITLE
Handle errors if Server hast no internet connection

### ISSUE THREAD

**Issue by jkroepke** [MinecraftForge/Mercurius#5] opened 2017-06-17 13:14 UTC
Server is behind a firewall.
Log:
```
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]: java.net.NoRouteToHostException: No route to host (Host unreachable)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.net.PlainSocketImpl.socketConnect(Native Method)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.net.Socket.connect(Socket.java:589)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.net.Socket.connect(Socket.java:538)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1022)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1020)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.security.AccessController.doPrivileged(Native Method)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1019)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:91)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1283)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1281)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.security.AccessController.doPrivileged(Native Method)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1280)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at net.minecraftforge.mercurius.Sender.post(Sender.java:125)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at net.minecraftforge.mercurius.Sender.access$000(Sender.java:25)
[15:12:00] [MercuriusThread/INFO] [STDERR/mercurius]: [net.minecraftforge.mercurius.Sender:post:147]:   at net.minecraftforge.mercurius.Sender$1.run(Sender.java:103)
```

**Comment by ironrainomega** [comment] 2017-06-18 16:10
This is a prime example of a very very bad bug report, and also a duplicate of #4.

**Closed as completed by ironrainomega** 2017-06-18 16:10 UTC

**Comment by jkroepke** [comment] 2017-06-18 16:19
Man forgotten exception handling is also pretty bad...

**Comment by ironrainomega** [comment] 2017-06-18 16:21
You would've crashed if the exception wouldn't be handled... it's just spamming your logs...

**Comment by jkroepke** [comment] 2017-06-18 16:28
I an agile way, just hide them. Nobody want to see logs from a call-to-home plugin. It should be fail silence or print strackstraces on the debug level.
